#!/bin/sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
HOST_TASK_ROOT="${TMPDIR:-/tmp}/acmesh-console-host-tests.$$"
export ACMESH_TASK_STATE_DIR="$HOST_TASK_ROOT/state"
export ACMESH_TASK_LOG_DIR="$HOST_TASK_ROOT/log"
trap 'rm -rf "$HOST_TASK_ROOT"' 0 HUP INT TERM
mkdir -p "$ACMESH_TASK_STATE_DIR" "$ACMESH_TASK_LOG_DIR"
chmod 700 "$HOST_TASK_ROOT" "$ACMESH_TASK_STATE_DIR" "$ACMESH_TASK_LOG_DIR"
. "$ROOT/tests/lib/host_flock.sh"
acmesh_test_install_flock_shim "$HOST_TASK_ROOT/flock"
acmesh_test_install_private_ls_shim "$HOST_TASK_ROOT/private-ls" "$HOST_TASK_ROOT"

sh "$ROOT/tests/test_private_io.sh"
sh "$ROOT/tests/test_request_transport.sh"
sh "$ROOT/tests/test_acmeshctl_request_file.sh"
sh "$ROOT/tests/test_runtime_library_path.sh"
sh "$ROOT/tests/test_conf_parser.sh"
sh "$ROOT/tests/test_status_scan.sh"
sh "$ROOT/tests/test_task.sh"
sh "$ROOT/tests/test_task_recovery.sh"
sh "$ROOT/tests/test_config_schema.sh"
sh "$ROOT/tests/test_profile_resolution.sh"
sh "$ROOT/tests/test_authorization_fingerprint.sh"
sh "$ROOT/tests/test_authorization_ledger.sh"
sh "$ROOT/tests/test_authorization_concurrency.sh"
sh "$ROOT/tests/test_operation_admission.sh"
sh "$ROOT/tests/test_secure_migration.sh"
sh "$ROOT/tests/test_destructive_authorization.sh"
sh "$ROOT/tests/test_profile_signal_cleanup.sh"
sh "$ROOT/tests/test_config_profiles.sh"
sh "$ROOT/tests/test_command_builder.sh"
sh "$ROOT/tests/test_issue_staging_ca.sh"
sh "$ROOT/tests/test_issue_account_email.sh"
sh "$ROOT/tests/test_issue_test_mode.sh"
sh "$ROOT/tests/test_issue_real_mode.sh"
sh "$ROOT/tests/test_issue_missing_acme.sh"
sh "$ROOT/tests/test_renew.sh"
sh "$ROOT/tests/test_core_status.sh"
sh "$ROOT/tests/test_core_install_mode.sh"
sh "$ROOT/tests/test_core_install_requires_openssl.sh"
sh "$ROOT/tests/test_core_upgrade_mode.sh"
sh "$ROOT/tests/test_core_upgrade_rollback.sh"
sh "$ROOT/tests/test_import_history.sh"
sh "$ROOT/tests/test_i18n_support.sh"
sh "$ROOT/tests/test_provider_templates.sh"
sh "$ROOT/tests/test_dns_provider_contracts.sh"
sh "$ROOT/tests/test_dns_official_candidates.sh"
sh "$ROOT/tests/test_dns_test.sh"
sh "$ROOT/tests/test_cloudflare_optional_ids.sh"
sh "$ROOT/tests/test_no_legacy_views.sh"
sh "$ROOT/tests/test_operations_dns_credentials.sh"
sh "$ROOT/tests/test_operations_defaults_entry_ui.sh"
sh "$ROOT/tests/test_operations_profile_edit_ui.sh"
sh "$ROOT/tests/test_profile_execution_ui_contract.sh"
sh "$ROOT/tests/test_authorization_ui.sh"
sh "$ROOT/tests/test_certificates_list_detail_ui.sh"
sh "$ROOT/tests/test_logs_list_detail_ui.sh"
sh "$ROOT/tests/test_deploy_install.sh"
sh "$ROOT/tests/test_deploy_hook_registration.sh"
sh "$ROOT/tests/test_deploy_hook_authorization.sh"
sh "$ROOT/tests/test_deploy_transaction.sh"
sh "$ROOT/tests/test_ssh_key.sh"
sh "$ROOT/tests/test_ssh_security.sh"
sh "$ROOT/tests/test_ssh_test_mode.sh"
sh "$ROOT/tests/test_rpc_boundaries.sh"
sh "$ROOT/tests/test_rpc_core_methods.sh"
sh "$ROOT/tests/test_cli_authorization.sh"
sh "$ROOT/tests/test_package_contract.sh"

echo "all host tests passed"
