#!/bin/sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
PAGE="$ROOT/htdocs/luci-static/resources/view/acmesh/operations_v2.js"

require_text() {
	needle="$1"
	if ! grep -Fq -- "$needle" "$PAGE"; then
		echo "operations page missing: $needle"
		exit 1
	fi
}

require_text "DNS_PROVIDER_TEMPLATES"
require_text "Cloudflare API Token"
require_text "Cloudflare Global API Key"
require_text "CF_Token"
require_text "CF_Email"
require_text "CF_Key"
require_text "credentialMode"
require_text "credentials"
require_text "validateIssueProfile"
require_text "runTask('dns_test', { profileId: profile.id })"
require_text "Custom credentials"
require_text "acmesh-custom-credentials"
require_text "credentialEnvLooksSecret"
require_text "_SK"
require_text "split(/\\r?\\n/)"
require_text "OFFICIAL_DNS_API_CANDIDATES"
require_text "Official DNS API filter"
require_text "Official DNS API candidates"
require_text "Select official DNS API"
require_text "renderOfficialDnsCandidates"
require_text "dns_1984hosting"
require_text "dns_baidu"
require_text "dns_cloudns"
require_text "dns_gcore"
require_text "dns_la"
require_text "dns_namecom"
require_text "dns_namesilo"
require_text "dns_nsone"
require_text "dns_spaceship"
require_text "dns_vercel"
require_text "dns_volcengine"
require_text "dns_zonomi"
require_text "Baidu_AK"
require_text "CLOUDNS_AUTH_ID"
require_text "GCORE_Key"
require_text "LA_Id"
require_text "Namecom_Username"
require_text "Namesilo_Key"
require_text "NS1_Key"
require_text "SPACESHIP_API_KEY"
require_text "VERCEL_TOKEN"
require_text "runTask('dns_test'"
require_text "DNS Test"
require_text "waitTask"
require_text "deploy-run"
require_text "const operation = deployAfterIssue ? 'issue-deploy' : 'issue';"
require_text "summarizeTaskLog"
require_text "invalidContact"
require_text "Error adding TXT record"
require_text "invalid domain"
require_text "importHistoryProfiles"
require_text "keyTypeFromAcme"
require_text "caFromAcmeApi"
require_text "Imported issue profiles"
require_text "SECRET_PLACEHOLDER"
require_text "data-acmesh-secret-placeholder"
require_text "mode.fields.some(function(field) { return rawVars[field.env]; })"

echo "test_operations_dns_credentials: ok"
